version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '${ELASTICS_REST_PORT}:9200'
      - '${ELASTICS_NODE_COMMUNICATION_PORT}:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - '${LOGSTASH_BEATS_PORT}:5044'
      - '${LOGSTASH_TCP_PORT}:5000/tcp'
      - '${LOGSTASH_UPD_PORT}:5000/udp'
      - '${LOGSTASH_WEB_API_PORT}:9600'
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - '${KIBANA_HTTP_PORT}:5601'
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
